### ISSUE TITLE
Suggested Edit: Label/Detect Identical Content 

### ISSUE THREAD

**Issue by Paycho** [gbdubs/focusonfeaturesdata#7]
Suggested Edit For [Label/Detect Identical Content ](https://fellowship.ii.grady.dev/intervention/identical-content) (ID: /intervention/identical-content)

## Your Suggestion(s) for this page 

The definition is missing an "is": For some types of harm, the same data [is] a strong signal of something being off.

**Comment by gbdubs** [comment]
Fixed! Thanks Paycho!
